allowBuilds:
  esbuild: true
  sharp: true
  workerd: true
minimumReleaseAgeExclude:
  - '@sveltejs/adapter-cloudflare@7.2.9'
  - '@sveltejs/kit@2.65.2'
  - '@sveltia/cms@0.167.2 || 0.172.3'
  - prettier@3.9.1
  - '@antfu/eslint-config@9.2.0'
