import { createPlayer } from '../equipment/mediaSupport.js'
import { soundCandidates } from './soundPaths.js'
import { log } from '@zos/utils'

// Module-level so the map isn't rebuilt on every play() call.
const SOUNDS = {
  success: 'success.opus',
  error: 'error.opus',
  warning: 'warning.opus',
  notification: 'notification.opus',
  info: 'info.opus',
  click: 'click.opus'
}

export class SoundFeedback {
  constructor(defaultVolume = 50) {
    this.volume = Math.min(Math.max(defaultVolume, 0), 100)
    this.player = null
    this.initialized = false
    this._prepareHandler = null
  }

  init() {
    if (this.initialized) return true
    try {
      // null on firmware without '@zos/media' (API_LEVEL < 3.0): stay
      // uninitialized so sounds are skipped silently and haptics still work.
      this.player = createPlayer()
      this.initialized = this.player !== null
      return this.initialized
    } catch (error) {
      log.error('Failed to create audio player:', error)
      return false
    }
  }

  setVolume(volume) {
    this.volume = Math.min(Math.max(volume, 0), 100)
    if (this.player) this.player.setVolume(this.volume)
  }

  async play(sound) {
    // Master on/off lives on the "Feedback" screen (settingsKey
    // 'soundFeedbackEnabled') since that's what this class already gates
    // event-driven confirmation/error sounds behind.
    const config = globalThis.ScreenReaderConfig || {}
    if (config.soundFeedbackEnabled === false) {
      return
    }

    if (!this.initialized && !this.init()) return
    if (!this.player) return

    try {
      const soundFile = SOUNDS[sound]
      if (!soundFile) {
        log.warn(`Invalid sound type: ${sound}`)
        return
      }

      // Detach any previous prepare handler to avoid leaking listeners
      // across back-to-back play() calls.
      if (this._prepareHandler) {
        try {
          this.player.removeEventListener(this.player.event.PREPARE, this._prepareHandler)
        } catch (_e) {
          // ignore — some SDKs throw when removing an inactive listener
        }
        this._prepareHandler = null
      }

      // "Master Volume" (settingsKey 'masterVolume', 0-100, from
      // setting/volumeSetting.js) applies here since this player is the
      // only place ZSR plays non-speech audio.
      if (typeof config.masterVolume === 'number') {
        this.setVolume(config.masterVolume)
      }

      // "Sound Theme" (settingsKey 'soundTheme', from
      // setting/SoundSetting.js) selects which asset subfolder to load
      // from - Jieshuo calls this concept "Sound Schemes". The 'default'
      // theme keeps the original flat assets/raw/audio/*.opus layout so
      // existing installs need no new files; 'classic'/'minimal' expect
      // assets/raw/audio/<theme>/*.opus (generated by
      // tools/generate_earcons.py). If a file cannot be prepared, this logs a
      // warning instead of throwing (see the PREPARE handler below).
      const theme = config.soundTheme && config.soundTheme !== 'default' ? config.soundTheme : null
      const candidates = soundCandidates(soundFile, theme)
      let attempt = 0

      const onPrepare = (result) => {
        log.info('Sound prepare result:', result)
        if (result && this.player) {
          this.player.start()
        } else if (!result && attempt < candidates.length) {
          // Firmware differs in how it resolves bundled paths: try the next form.
          try {
            this.player.stop()
            this.player.setSource(this.player.source.FILE, { file: candidates[attempt++] })
            this.player.prepare()
          } catch (e) {
            log.warn('SoundFeedback: could not load sound: ' + String(e))
          }
          return
        } else if (!result) {
          log.warn(`SoundFeedback: could not prepare "${soundFile}" from any known path`)
        }
        if (this.player) {
          try {
            this.player.removeEventListener(this.player.event.PREPARE, onPrepare)
          } catch (_e) {
            // ignore
          }
        }
        this._prepareHandler = null
      }

      this.player.stop()
      this.player.setSource(this.player.source.FILE, { file: candidates[attempt++] })

      this._prepareHandler = onPrepare
      this.player.addEventListener(this.player.event.PREPARE, onPrepare)
      this.player.prepare()
    } catch (error) {
      log.error('Sound playback failed:', error)
    }
  }

  stop() {
    if (this.player) this.player.stop()
  }

  release() {
    if (this.player) {
      this.player.stop()
      this.player.release()
      this.player = null
      this.initialized = false
    }
  }
}

export default new SoundFeedback()
