backend:
  name: github
  repo: NVCDevelopmentTeam/Zepp-OS-ScreenReader/tree/main/site/htdocs
  base_url: https://zsr.net
  branch: main

media_folder: "static/uploads"
public_folder: "/uploads"

collections:
  - name: "posts"
    label: "Posts"
    folder: "src/lib/posts"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Body", name: "body", widget: "markdown"}
